run:
	@CUDA_VER=11.4 OPENCV=1 make -C nvdsinfer_custom_impl_Yolo

# Execute "make rgb"

# rgb:
# 	@deepstream-app -c rgb.txt

# rgb_save:
# 	@deepstream-app -c rgbsave.txt

# # Execute "make thermal"

# thermal:
# 	@deepstream-app -c thermal.txt

# thermal_save:
# 	@deepstream-app -c thermalsave.txt
